meta:
    logdir: /work/inestp02/xipe_markus/self-expanding-neural-networks/senn_mlp/logs
    name: logs
data:
  root: /work/inestp02/xipe_markus/self-expanding-neural-networks/senn_mlp/datasets
  defaults:
    root: /work/inestp02/xipe_markus/self-expanding-neural-networks/senn_mlp/datasets
checkpointing:
  directory: /work/inestp02/xipe_markus/self-expanding-neural-networks/senn_mlp/checkpoints
